var publications = [
  {
    year: "2023",
    type: "Journal",
    domain: "Medical AI",
    title: "CovidExpert: A Triplet Siamese Neural Network framework for the detection of COVID-19",
    venue: "Informatics in Medicine Unlocked, 101156. DOI: 10.1016/j.imu.2022.101156",
    citations: 22,
    summary:
      "A medical imaging study on CT-based COVID-19 detection, using pretrained CNN features and a Triplet Siamese Network for limited-data diagnosis support.",
    tags: ["Few-shot learning", "Siamese networks", "CT imaging", "CNN features"],
    logo: "https://cdn.simpleicons.org/elsevier",
    visualClass: "paper-medical",
    visualSteps: ["CT", "CNN", "Siamese"],
    link: "https://doi.org/10.1016/j.imu.2022.101156",
  },
  {
    year: "2025",
    type: "Journal",
    domain: "OCR",
    title:
      "Optical character recognition for ancient scripts: a case study on Syloti Nagri using deep learning models",
    venue: "Journal of Computer Sciences Institute",
    citations: 1,
    summary:
      "A low-resource OCR pipeline for Syloti Nagri, combining segmentation and deep learning to support recognition of an underrepresented script.",
    tags: ["OCR", "Low-resource scripts", "Segmentation", "Deep learning"],
    logo: "https://cdn.simpleicons.org/googlescholar",
    visualClass: "paper-document",
    visualSteps: ["Scan", "Segment", "Recognize"],
    link: "https://ph.pollub.pl/index.php/jcsi/article/view/6785",
  },
  {
    year: "2025",
    type: "Journal",
    domain: "Document AI",
    title:
      "Advancing Bangla typography: machine learning and transfer learning based font detection and classification approach using the Bang-laFont45 dataset",
    venue: "Journal of Computer Sciences Institute",
    citations: 0,
    summary:
      "A Bangla document AI project focused on font detection and classification, using machine learning and transfer learning with the Bang-laFont45 dataset.",
    tags: ["Bangla computing", "Font recognition", "Transfer learning", "Document AI"],
    logo: "https://cdn.simpleicons.org/googlescholar",
    visualClass: "paper-document",
    visualSteps: ["Font", "Features", "Classify"],
    link: "https://ph.pollub.pl/index.php/jcsi/article/view/7120",
  },
  {
    year: "2025",
    type: "Conference",
    domain: "Safety",
    title:
      "Enhancing Concrete Performance: Machine Learning Models for Predicting and Classifying Tensile Strength",
    venue: "ECCE 2025, IEEE",
    citations: 0,
    summary:
      "A civil engineering AI study using machine learning to predict and classify concrete tensile strength for material performance analysis.",
    tags: ["Civil AI", "Prediction", "Classification", "Engineering safety"],
    logo: "https://cdn.simpleicons.org/ieee",
    visualClass: "paper-safety",
    visualSteps: ["Data", "Model", "Risk"],
    link: "https://ieeexplore.ieee.org/document/11013991/",
  },
  {
    year: "2024",
    type: "Conference",
    domain: "Safety",
    title: "CrackClassification4: Classifying Four Types of Cracks in Structural Surfaces Using CNNs",
    venue: "ICCIT 2024, IEEE",
    citations: 0,
    summary:
      "A computer vision project for structural inspection, classifying four surface-crack types with CNN models.",
    tags: ["Structural CV", "CNNs", "Inspection", "Crack classification"],
    logo: "https://cdn.simpleicons.org/ieee",
    visualClass: "paper-safety",
    visualSteps: ["Image", "CNN", "Crack type"],
    link: "https://ieeexplore.ieee.org/document/11022574/",
  },
  {
    year: "2024",
    type: "Conference",
    domain: "NLP",
    title: "Optimizing Multilingual Summarization: Advanced Corpus Creation and Filtering Approach",
    venue: "ICCIT 2024, IEEE",
    citations: 1,
    summary:
      "A dataset-building study for multilingual summarization, using LaBSE, ROUGE, BLEU, and BERTScore to filter 567,462 high-quality instances.",
    tags: ["NLP", "Dataset creation", "Filtering", "Summarization"],
    logo: "https://cdn.simpleicons.org/ieee",
    visualClass: "paper-nlp",
    visualSteps: ["Translate", "Score", "Filter"],
    link: "https://www.researchgate.net/profile/Md-Mehrab-Hossain-2/publication/392564595_Optimizing_Multilingual_Summarization_Advanced_Corpus_Creation_and_Filtering_Approach/links/6852635e7869fe75c55a1101/Optimizing-Multilingual-Summarization-Advanced-Corpus-Creation-and-Filtering-Approach.pdf",
  },
  {
    year: "2025",
    type: "Conference",
    domain: "Agriculture",
    title:
      "DateFNet: From Pixels to Plates - Attention Based Multi-Stream CNN for Date Fruit Classification",
    venue: "ICCIT 2025, IEEE",
    citations: 0,
    summary:
      "A fine-grained agricultural vision study using a three-stream attention-based CNN to classify 14 date fruit varieties.",
    tags: ["Food classification", "Multi-stream CNN", "Attention", "Agricultural AI"],
    logo: "https://cdn.simpleicons.org/ieee",
    visualClass: "paper-agri",
    visualSteps: ["Fruit", "Attention", "Class"],
    link: "https://www.researchgate.net/profile/Munshaibur-Rahman-Mahin/publication/404606572_DateFNet_From_Pixels_to_Plates-Attention_Based_Multi-Stream_CNN_for_Date_Fruit_Classification/links/6a0199d8e93d46191595be16/DateFNet-From-Pixels-to-Plates-Attention-Based-Multi-Stream-CNN-for-Date-Fruit-Classification.pdf",
  },
  {
    year: "2025",
    type: "Conference",
    domain: "Safety",
    title:
      "Deep Learning-Based Detection of Aircraft Cracks and Dents Using YOLOv11 and YOLOv12 for Aviation Safety in Bangladesh",
    venue: "ICCIT 2025, IEEE",
    citations: 0,
    summary:
      "First deep learning study on aircraft surface defect detection in Bangladesh, benchmarking YOLOv11 and YOLOv12 on 9,994 annotated images. YOLOv12 achieved 76.3% precision and 69.3% mAP@50, establishing a baseline for scalable aviation safety inspection.",
    tags: ["Object detection", "YOLOv12", "Aviation safety", "Structural inspection"],
    logo: "https://cdn.simpleicons.org/ieee",
    visualClass: "paper-safety",
    visualSteps: ["Image", "YOLO", "Defect"],
    link: "https://www.researchgate.net/publication/398123868_Deep_Learning-Based_Detection_of_Aircraft_Cracks_and_Dents_Using_YOLOv11_and_YOLOv12_for_Aviation_Safety_in_Bangladesh",
  },
];
